# Generated by Django 3.2.2 on 2021-06-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210617_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='commented',
            new_name='comments',
        ),
    ]
