# Generated by Django 3.2.2 on 2021-06-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_commented_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
