# Generated by Django 3.2.2 on 2021-06-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='images/users/%Y/%m/%d'),
        ),
    ]
