# Generated by Django 3.2.2 on 2021-06-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210616_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
